/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNIlib */

#ifndef _Included_JNIlib
#define _Included_JNIlib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNIlib
 * Method:    PM_create
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_JNIlib_PM_1create
  (JNIEnv *, jclass, jint);

/*
 * Class:     JNIlib
 * Method:    PM_destroy
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_JNIlib_PM_1destroy
  (JNIEnv *, jclass);

/*
 * Class:     JNIlib
 * Method:    PM_parseFrom
 * Signature: (Ljava/lang/String;C)I
 */
JNIEXPORT jint JNICALL Java_JNIlib_PM_1parseFrom
  (JNIEnv *, jclass, jstring, jchar);

/*
 * Class:     JNIlib
 * Method:    PM_manage
 * Signature: (Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_JNIlib_PM_1manage
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     JNIlib
 * Method:    hasValue
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_JNIlib_hasValue
  (JNIEnv *, jclass, jstring);

/*
 * Class:     JNIlib
 * Method:    getValue
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JNIlib_getValue
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     JNIlib
 * Method:    getListSize
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_JNIlib_getListSize
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
